@startwbs Древовидная диаграмма - Веб-приложение для аптечной сети

title Древовидная диаграмма причин задержек\nРазработка веб-приложения для аптечной сети

* Причины задержек разработки
** Технические проблемы
*** Интеграция платежных систем
**** Сложность API ЮKassa
**** Требования безопасности PCI DSS
*** Интеграция с ЕГИСЗ
**** Бюрократические процедуры
**** Нестабильное API
*** Работа с электронными рецептами
**** Распознавание OCR
**** Валидация форматов
** Кадровые проблемы
*** Дефицит специалистов
**** Высокий спрос на рынке
**** Специфические навыки (медицина + IT)
*** Выгорание команды
**** Высокая нагрузка
**** Сжатые сроки
*** Недостаточная квалификация
**** Незнание фармацевтики
**** Отсутствие опыта в медсистемах
** Организационные проблемы
*** Затяжные согласования
**** Многоуровневая иерархия
**** Бюрократия
*** Высокая нагрузка на архитектора
**** Все решения через одного человека
**** Недостаточное делегирование
** Системные проблемы
*** Сложность архитектуры
**** Множество интеграций
**** Микросервисная архитектура
*** Человеческий фактор
**** Ошибки в оценках
**** Коммуникационные проблемы
** Ресурсные проблемы
*** Низкая мотивация
**** Неясные цели проекта
**** Отсутствие обратной связи

@endwbs
