@startuml Process Specification

skinparam rectangleBackgroundColor White
skinparam rectangleBorderColor Black
skinparam actorBackgroundColor White
skinparam actorBorderColor Black

title Спецификация процесса: Оформление заказа в аптечном приложении

|Пользователь|
start
:Открывает приложение;
:Ищет нужные лекарства;
:Добавляет товары в корзину;
:Выбирает способ получения\n(Самовывоз / Доставка);

if (Выбрана доставка?) then (да)
  :Указывает адрес доставки;
else (нет)
  :Выбирает аптеку на карте;
endif

:Выбирает способ оплаты;

|Мобильное приложение|
:Формирует заказ;
:Отправляет данные на сервер;

|API-сервер|
:Создаёт заказ в БД;
:Проверяет наличие товаров;

if (Товары в наличии?) then (нет)
  |Мобильное приложение|
  :Уведомление:\n"Товара нет в наличии";
  stop
else (да)
  :Резервирует товары;
endif

if (Способ оплаты онлайн?) then (да)
  |Платёжная система|
  :Обрабатывает платёж;
  
  if (Платёж успешен?) then (нет)
    |Мобильное приложение|
    :Уведомление:\n"Ошибка оплаты";
    stop
  else (да)
    :Подтверждает оплату;
  endif
endif

|API-сервер|
:Отправляет заказ в аптеку;
:Push-уведомление пользователю:\n"Заказ принят";

|Аптека|
:Получает заказ;
:Проверяет рецепты\n(если требуется);
:Фармацевт собирает заказ;
:Упаковывает товары;

if (Способ получения?) then (Самовывоз)
  :Размещает заказ\nв зоне выдачи;
  |API-сервер|
  :Push-уведомление:\n"Заказ готов к выдаче";
  |Пользователь|
  :Приходит в аптеку;
  :Предъявляет код заказа;
  |Аптека|
  :Выдаёт заказ;
  if (Оплата при получении?) then (да)
    :Принимает оплату;
  endif
else (Доставка)
  |Курьер|
  :Принимает заказ;
  :Доставляет по адресу;
  |Пользователь|
  :Получает заказ;
  if (Оплата при получении?) then (да)
    |Курьер|
    :Принимает оплату;
  endif
endif

|API-сервер|
:Обновляет статус:\n"Завершён";
:Начисляет бонусы;
:Отправляет запрос на отзыв;

|Пользователь|
:Получает уведомление\nо завершении заказа;

stop

@enduml