stateDiagram-v2
    [*] --> ОткрытиеПриложения: Пользователь запускает приложение
    
    ОткрытиеПриложения --> ПроверкаАвторизации: Загрузка
    
    ПроверкаАвторизации --> ГлавнаяСтраница: Авторизован
    ПроверкаАвторизации --> ОшибкаАвторизации: Не авторизован
    
    ОшибкаАвторизации --> [*]: Вход в систему требуется
    
    ГлавнаяСтраница --> ПоискЛекарств: Выбор поиска
    ГлавнаяСтраница --> УправлениеРецептами: Выбор рецептов
    ГлавнаяСтраница --> ОформлениеЗаказа: Выбор корзины
    
    state ПоискЛекарств {
        [*] --> ВводПоискового: Пользователь вводит название
        ВводПоискового --> ЗапросПоиска: Отправка запроса
        ЗапросПоиска --> ОтображениеРезультатов: Получение данных
        ОтображениеРезультатов --> ВыборЛекарства: Выбор препарата
        ВыборЛекарства --> ПроверкаНаличия: Проверка в аптеках
        ПроверкаНаличия --> ДобавлениеВКорзину: В наличии
        ПроверкаНаличия --> УведомлениеОПоступлении: Нет в наличии
        ДобавлениеВКорзину --> [*]
        УведомлениеОПоступлении --> [*]
    }
    
    state УправлениеРецептами {
        [*] --> ВыборДействия: Открытие раздела
        ВыборДействия --> ЗагрузкаРецепта: Загрузить рецепт
        ВыборДействия --> ПросмотрРецептов: Мои рецепты
        ВыборДействия --> ПроверкаСрока: Проверить срок
        
        ЗагрузкаРецепта --> ВалидацияРецепта: Проверка
        ВалидацияРецепта --> СохранениеРецепта: Действителен
        ВалидацияРецепта --> ОшибкаРецепта: Недействителен
        
        ПросмотрРецептов --> ОтображениеСписка: Список рецептов
        ОтображениеСписка --> [*]
        
        ПроверкаСрока --> УведомлениеОСроке: Результат проверки
        УведомлениеОСроке --> [*]
        
        СохранениеРецепта --> [*]
        ОшибкаРецепта --> [*]
    }
    
    state ОформлениеЗаказа {
        [*] --> ПросмотрКорзины: Открытие корзины
        ПросмотрКорзины --> РедактированиеКорзины: Изменение количества
        РедактированиеКорзины --> ПросмотрКорзины: Обновление
        
        ПросмотрКорзины --> ВыборСпособаПолучения: Оформить заказ
        ВыборСпособаПолучения --> ВыборАптеки: Самовывоз
        ВыборСпособаПолучения --> ВводАдреса: Доставка
        
        ВыборАптеки --> ПроверкаНаличияВАптеке: Выбрана аптека
        ВводАдреса --> РасчетДоставки: Адрес введен
        
        ПроверкаНаличияВАптеке --> ВыборОплаты: Товар доступен
        ПроверкаНаличияВАптеке --> ПредложениеАльтернатив: Товар недоступен
        
        РасчетДоставки --> ВыборОплаты: Доставка возможна
        РасчетДоставки --> ПредложениеАльтернатив: Доставка невозможна
        
        ПредложениеАльтернатив --> ВыборАптеки: Выбор другой аптеки
        ПредложениеАльтернатив --> [*]: Отмена
        
        ВыборОплаты --> ОплатаОнлайн: Онлайн оплата
        ВыборОплаты --> ОплатаПриПолучении: Оплата при получении
        
        ОплатаОнлайн --> ПодтверждениеОплаты: Обработка платежа
        ПодтверждениеОплаты --> СозданиеЗаказа: Успешно
        ПодтверждениеОплаты --> ОшибкаОплаты: Ошибка
        
        ОплатаПриПолучении --> СозданиеЗаказа: Подтверждение
        
        СозданиеЗаказа --> УведомлениеОЗаказе: Заказ создан
        УведомлениеОЗаказе --> [*]
        
        ОшибкаОплаты --> ВыборОплаты: Повторить
        ОшибкаОплаты --> [*]: Отменить
    }
    
    ПоискЛекарств --> ГлавнаяСтраница: Возврат
    УправлениеРецептами --> ГлавнаяСтраница: Возврат
    ОформлениеЗаказа --> ГлавнаяСтраница: Возврат
