stateDiagram-v2
    [*] --> Создан : Пользователь<br/>оформляет заказ
    
    Создан --> ОжидаетОплаты : Выбран способ<br/>оплаты онлайн
    Создан --> ПринятВОбработку : Выбрана оплата<br/>при получении
    Создан --> Отменён : Пользователь<br/>отменяет заказ
    
    ОжидаетОплаты --> Оплачен : Платёж<br/>успешно проведён
    ОжидаетОплаты --> Отменён : Ошибка оплаты<br/>или тайм-аут
    
    Оплачен --> ПринятВОбработку : Аптека получает<br/>уведомление
    
    ПринятВОбработку --> Готовится : Фармацевт<br/>начинает сборку
    
    Готовится --> ГотовКВыдаче : Заказ собран<br/>(самовывоз)
    Готовится --> ГотовКДоставке : Заказ собран<br/>(доставка)
    Готовится --> Отменён : Товара нет<br/>в наличии
    
    ГотовКВыдаче --> Выдан : Клиент забрал<br/>заказ в аптеке
    ГотовКВыдаче --> Отменён : Клиент не забрал<br/>в течение 3 дней
    
    ГотовКДоставке --> ВДоставке : Курьер принял<br/>заказ
    
    ВДоставке --> Доставлен : Курьер доставил<br/>клиенту
    ВДоставке --> ГотовКДоставке : Неудачная<br/>попытка доставки
    
    Выдан --> Завершён : Заказ<br/>подтверждён
    Доставлен --> Завершён : Заказ<br/>подтверждён
    
    Завершён --> [*]
    Отменён --> [*]
